### ISSUE TITLE
Error when creating expiration rule

### ISSUE THREAD

**Issue by echiu64** [wimnat/ansible-modules#1]
Consider this playbook snip:

```
  tasks:
    - name: create test buckets
      s3:
        bucket: random-teapot-alskdjfghqpwoeiruty
        mode: create
        region: us-east-1

    - name: create test buckets
      s3:
        bucket: random-teapot-risderecbebifrisderecbebifkviggan4
        mode: create
        region: us-east-1

    - name: lifecycle create
      s3_lifecycle:
        name: random-teapot-alskdjfghqpwoeiruty
        region: us-east-1
        rule_id: myrule
        expiration_days: 30
        status: enabled
        state: present
```

I get this error when running:

```
TASK: [lifecycle create] ******************************************************
failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/Users/echiu/.ansible/tmp/ansible-tmp-1435892135.49-69343371736139/s3_lifecycle", line 3811, in <module>
    main()
  File "/Users/echiu/.ansible/tmp/ansible-tmp-1435892135.49-69343371736139/s3_lifecycle", line 403, in main
    create_lifecycle_rule(connection, module)
  File "/Users/echiu/.ansible/tmp/ansible-tmp-1435892135.49-69343371736139/s3_lifecycle", line 277, in create_lifecycle_rule
    if not appended:
UnboundLocalError: local variable 'appended' referenced before assignment

```

**Comment by echiu64** [comment]
"Works" when i remove rule_id, but when I check s3, there are no rules applied

**Comment by echiu64** [comment]
Looks like prefix is mandatory... should be able to specify a lifecycle w/o prefix, i.e. apply to entire bucket

**Comment by echiu64** [comment]
Same with delete using this playbook https://gist.github.com/echiu64/9a5ec48883cb32a0738f

**Comment by wimnat** [comment]
@echiu64 thanks for your testing.  I've pushed some changes which i hope will address the issues you described here.  If you don't define a prefix, it should indeed apply the rule to the whole bucket.

Let me know how the new version goes.

**Comment by echiu64** [comment]
Looks good, thanks. Here are some newer test cases issues...

Task

```
    - name: multi rule bucket 4 date and days
      s3_lifecycle:
        name: random-teapot-{{ bucket2_name }}
        region: us-east-1
        expiration_days: 30
        expiration_date: 2020-12-30
```

Error

```
TASK: [multi rule bucket 4 date and days] *************************************
fatal: [localhost] => Traceback (most recent call last):
  File "/Users/echiu/anaconda/lib/python2.7/site-packages/ansible/runner/__init__.py", line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/Users/echiu/anaconda/lib/python2.7/site-packages/ansible/runner/__init__.py", line 785, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/Users/echiu/anaconda/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1032, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/Users/echiu/anaconda/lib/python2.7/site-packages/ansible/runner/action_plugins/normal.py", line 57, in run
    return self.runner._execute_module(conn, tmp, module_name, module_args, inject=inject, complex_args=complex_args)
  File "/Users/echiu/anaconda/lib/python2.7/site-packages/ansible/runner/__init__.py", line 466, in _execute_module
    ) = self._configure_module(conn, module_name, args, inject, complex_args)
  File "/Users/echiu/anaconda/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1357, in _configure_module
    module_path, complex_args, module_args, inject
  File "/Users/echiu/anaconda/lib/python2.7/site-packages/ansible/module_common.py", line 151, in modify_module
    complex_args_json = utils.jsonify(complex_args)
  File "/Users/echiu/anaconda/lib/python2.7/site-packages/ansible/utils/__init__.py", line 222, in jsonify
    return json.dumps(result2, sort_keys=True, indent=indent, ensure_ascii=False)
  File "/Users/echiu/anaconda/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/Users/echiu/anaconda/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/Users/echiu/anaconda/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/Users/echiu/anaconda/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/Users/echiu/anaconda/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/Users/echiu/anaconda/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.date(2020, 12, 30) is not JSON serializable
```

Using `expiration_date: 2020-12-30T00:00:00` I the same error except the error message changes slightly:

```
TypeError: datetime.datetime(2020, 12, 30, 0, 0) is not JSON serializable
```

**Comment by wimnat** [comment]
Is that the exact task you used? expiration_date and expiration_days are defined as mutually exclusive in the module so you shouldn't be able to have them together in the same task. 

Also, as a workaround, try quoting the date time value.

**Comment by echiu64** [comment]
Yup that's exactly what I used... let me take that out and use date only. This was a test case to see what happens if I put both

**Comment by echiu64** [comment]
Quoting the date fixes the issue now

**Comment by echiu64** [comment]
For this playbook, i only expect changed=1

```
---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: create test buckets
      s3:
        bucket: random-teapot-alskdjfghqpwoeiruty
        mode: create
        region: us-east-1

    - name: lifecycle create
      s3_lifecycle:
        name: random-teapot-alskdjfghqpwoeiruty
        rule_id: myrule
        prefix: /p3
        region: us-east-1
        expiration_date: "2020-12-14T00:00:00"
        status: enabled
        state: present

    - name: lifecycle create
      s3_lifecycle:
        name: random-teapot-alskdjfghqpwoeiruty
        rule_id: myrule
        prefix: /p3
        region: us-east-1
        expiration_date: "2020-12-14T00:00:00"
        status: enabled
        state: present
```

Instead I get `changed=2` in the recap

**Comment by echiu64** [comment]
One new issue, probably an issue parsing the error for S3

```
    - name: expiration before transition
      s3_lifecycle:
        name: random-teapot-alskdjfghqpwoeiruty
        region: us-east-1
        expiration_date: "2020-12-01"
        transition_date: "2020-12-14"
```

Results in this error:

```
TASK: [expiration before transition] ******************************************
failed: [localhost] => {"failed": true}
msg: The XML you provided was not well-formed or did not validate against our published schema
```

**Comment by wimnat** [comment]
All the problems you are seeing are due to improper date formats.

You see two changes because the datetime format returned from Amazon includes the timezone whereas your string doesn't.  If you change your date to "2020-12-14T00:00:00.000Z" then you should only see one change.

The second issue is again due to date format.  Amazon will reject the XML because your date string does not include the time.

I'm not sure the best approach here.  I could try to manipulate the string that the user enters to make sure it is correct but there are lots of possibilities.  The other option is to make it clear in the documentation that the date needs to be in the correct format, including time and timezone.

**Comment by echiu64** [comment]
For the first issue... this playbook still has the 2 tasks returning as "changed", when only the first should have that returned:

```
    - name: lifecycle create
      s3_lifecycle:
        name: random-teapot-alskdjfghqpwoeiruty
        rule_id: myrule
        prefix: /p3
        region: us-east-1
        expiration_date: "2020-12-14T00:00:00.000Z"
        status: enabled
        state: present

    - name: lifecycle create
      s3_lifecycle:
        name: random-teapot-alskdjfghqpwoeiruty
        rule_id: myrule
        prefix: /p3
        region: us-east-1
        expiration_date: "2020-12-14T00:00:00.000Z"
        status: enabled
        state: present
```

The second one fails nicely now:

```
msg: 'Date' in the Expiration action for prefix '' must be later than 'Date' in the Transition action
```

I think just adding in some date validations would help... in pseudocode, something like

```
try:
   date.parse(datestr)
except DateFormatError: 
   module.fail("invalid date format for {}, format should be YYYY-MM-DD-etc ... ")
```

(Excuse the sloppy pseudocode)

**Comment by wimnat** [comment]
@echiu64 i've added in some better validation for the expiration and transition dates.

I can not reproduce your other issue.  If i run the playbook you specified above then i get one changed and then one ok...

PLAY [Test playbook] **********************************************************

TASK: [lifecycle create] ******************************************************
changed: [localhost]

TASK: [lifecycle create] ******************************************************
ok: [localhost]

**Comment by echiu64** [comment]
Same, everything looks good now!
